# Generated by GitHub Copilot
import json
import os
import time
from datetime import datetime

import pandas as pd
from kafka import KafkaConsumer

TOPIC_NAME = "airports_raw"
BOOTSTRAP_SERVERS = "localhost:9092"
GROUP_ID = "bronze-consumer-group"
BRONZE_PATH = "data/bronze/airports"
BATCH_SECONDS = 30


def ensure_directory(path: str) -> None:
    """Create the directory and any missing parents if they do not exist."""
    os.makedirs(path, exist_ok=True)


def flush_batch(records: list[dict]) -> None:
    """
    Persist a batch of raw Kafka records to Parquet (Bronze layer).

    Adds ingestion metadata columns (ingestion_date, ingestion_hour,
    ingested_at) and writes a time-stamped Parquet file under a
    date/hour partition path.

    :param records: List of deserialized message payloads from Kafka.
    """
    if not records:
        print("no records to flush")
        return

    ingestion_ts = datetime.utcnow()
    ingestion_date = ingestion_ts.strftime("%Y-%m-%d")
    ingestion_hour = ingestion_ts.strftime("%H")

    df = pd.DataFrame(records)
    df["ingestion_date"] = ingestion_date
    df["ingestion_hour"] = ingestion_hour
    df["ingested_at"] = ingestion_ts.isoformat()

    output_path = os.path.join(
        BRONZE_PATH,
        f"ingestion_date={ingestion_date}",
        f"ingestion_hour={ingestion_hour}",
    )
    ensure_directory(output_path)

    file_name = f"batch_{int(time.time())}.parquet"
    full_path = os.path.join(output_path, file_name)

    df.to_parquet(full_path, index=False)
    print(f"bronze written: {full_path} | rows={len(df)}")


def main():
    """
    Entry point for the Bronze consumer.

    Polls the Kafka topic in 30-second micro-batches and writes each
    batch as a Parquet file. Offset commit is manual and happens only
    after a successful write, ensuring at-least-once delivery semantics.
    """
    ensure_directory(BRONZE_PATH)

    consumer = KafkaConsumer(
        TOPIC_NAME,
        bootstrap_servers=BOOTSTRAP_SERVERS,
        group_id=GROUP_ID,
        auto_offset_reset="earliest",
        enable_auto_commit=False,
        value_deserializer=lambda value: json.loads(value.decode("utf-8")),
    )

    batch = []
    batch_start = time.time()

    try:
        while True:
            message_pack = consumer.poll(timeout_ms=1000)

            for _, messages in message_pack.items():
                for message in messages:
                    batch.append(message.value)

            if time.time() - batch_start >= BATCH_SECONDS:
                flush_batch(batch)
                consumer.commit()
                batch = []
                batch_start = time.time()

    except KeyboardInterrupt:
        print("stopping consumer...")
        if batch:
            flush_batch(batch)
            consumer.commit()
    finally:
        consumer.close()


if __name__ == "__main__":
    main()
